baseURL = "https://odiudang.com/"
defaultContentLanguage = "vi"
theme = "PaperMod"
title = "Ổ Dịu Dàng"
languageCode = "vi-VN"

enableRobotsTXT = true

[pagination]
pagerSize = 10

[params]
defaultTheme = "auto"

description = "Blog chia sẻ về học tập, ngoại ngữ, kế toán, Excel, Power BI và những trải nghiệm sống chậm mỗi ngày."
keywords = ["học tiếng Anh", "TOEIC", "Excel", "Power BI", "kế toán", "blog", "Ổ Dịu Dàng"]
author = "Ổ Dịu Dàng"
images = ["/images/og-cover.jpg"]

mainSections = ["posts"]

ShowReadingTime = true
ShowWordCount = true
ShowLastMod = true

ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true
ShowCodeCopyButtons = true

ShowFullTextinRSS = true


[params.homeInfoParams]
Title = "🌿 Ổ Dịu Dàng"

Content = """
Một góc nhỏ để lưu lại những điều đã học,
những kinh nghiệm đã trải qua
và những bài học vẫn đang tiếp tục khám phá.

Hy vọng nơi này sẽ đồng hành cùng bạn
trên hành trình học tập, phát triển
và sống chậm hơn mỗi ngày.
"""

[[menu.main]]
identifier = "home"
name = "Trang Chủ"
url = "/"
weight = 10

[[menu.main]]
identifier = "study"
name = "Góc Học Hành"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "resources"
name = "Góc Tài Nguyên"
url = "/resources/"
weight = 30

[[menu.main]]
identifier = "life"
name = "Góc Linh Tinh"
url = "/life/"
weight = 40

[taxonomies]
tag = "tags"
category = "categories"
[outputs]
home = ["HTML", "RSS", "JSON"]
[services]
  [services.googleAnalytics]
    id = "G-G5J593EPRY"